
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basic1__dev?serverTimezone=Asia/Seoul
    username: codelion
    password: Ll14130635@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  resources:
    add-mappings=false:
