
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basic1__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: codelion
    password: Ll14130635@@
  jpa:
    hibernate:
      ddl-auto: create # DB 테이블 자동생성(엔티티 클래스만 만들면 됨)
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
